cp -r outputs0jet/output_category_0jet_data_run_2_nominal.root REAL_DATA_PRODv11/.
cp -r outputs1jet_lowpt4l/output_category_1jet_lowpt4l_data_run_2_nominal.root REAL_DATA_PRODv11/. 
cp -r outputs1jet_mediumpt4l/output_category_1jet_mediumpt4l_data_run_2_nominal.root REAL_DATA_PRODv11/. 
cp -r outputs1jet_highpt4l/output_category_1jet_highpt4l_data_run_2_nominal.root REAL_DATA_PRODv11/. 
cp -r outputs2jet_VH_lowpt4l/output_category_2jet_VH_lowpt4l_data_run_2_nominal.root REAL_DATA_PRODv11/. 
cp -r outputs2jet_VH_highpt4l/output_category_2jet_VH_highpt4l_data_run_2_nominal.root REAL_DATA_PRODv11/. 
cp -r outputs2jet_VBF_lowptjet/output_category_2jet_VBF_lowptjet_data_run_2_nominal.root REAL_DATA_PRODv11/. 
cp -r outputs2jet_VBF_highptjet/output_category_2jet_VBF_highptjet_data_run_2_nominal.root REAL_DATA_PRODv11/.
cp -r outputsVHlep/output_category_VHlep_data_run_2_nominal.root REAL_DATA_PRODv11/. 
cp -r outputsttH/output_category_ttH_data_run_2_nominal.root REAL_DATA_PRODv11/. 

